# Generated by Django 4.1.4 on 2023-01-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/developers'),
        ),
    ]
