# Generated by Django 4.1.4 on 2023-01-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('framework', models.CharField(max_length=6000)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
