# Generated by Django 4.1.4 on 2023-01-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_newposts_newpost_alter_newpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='framework',
            field=models.CharField(max_length=6000, verbose_name='Post Content'),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Post name'),
        ),
    ]
