# Generated by Django 4.1.4 on 2023-01-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_newpost_framework_alter_newpost_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPost',
        ),
    ]
