# Generated by Django 4.1.4 on 2023-01-31 17:53

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_developer_date_created_developer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
    ]
